spring:
  application:
    name: @project.artifactId@
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true
        default_schema: autenticacao
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dbautenticacao?currentSchema=autenticacao
    username: user_autenticacao
    password: user_autenticacao
    hikari:
      maximum-pool-size: 10
      max-lifetime: 300000
  flyway:
    enabled: true
    table: FLYWAY_SCHEMA_HISTORY
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    placeholders:
      SCHEMA_NAME: autenticacao
      APP_USER: ${spring.datasource.username}
#    clean-on-validation-error: on
#    clean-disabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

cors:
  allowedOrigins: '*'

server:
  port: 8081
  address: 0.0.0.0
  tomcat:
    max-http-form-post-size: 100MB
    connection-timeout: 6000

#LOGGER
logging:
  file:
    name: @project.artifactId@.log
    path: @project.basedir@
  level:
    org.springframework.web: INFO
    org.hibernate: INFO
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.hibernate.stat: DEBUG
#    org.flywaydb: TRACE
#    org.flywaydb.core.internal.dbsupport.SqlScript: TRACE

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: pucminas
  resource: admin-app
  public-client: true
  use-resource-role-mappings: true
  credentials:
    secret: eFbr2PlVXUMoAmEXJmNUo7djw4FoHvXf
