CREATE TABLE ${SCHEMA_NAME}.TAB_PERFIL
(
    IDT_PERFIL    BIGINT       NOT NULL,
    NM_PERFIL     VARCHAR(80)  NOT NULL,
    DS_PERFIL     VARCHAR(254) NOT NULL,
    SGL_PERFIL    VARCHAR(25)  NOT NULL,
    FLG_ATIVO     VARCHAR(1)   NOT NULL,
    DAT_INCLUSAO  TIMESTAMP    NOT NULL,
    DAT_ALTERACAO TIMESTAMP
);

COMMENT ON TABLE ${SCHEMA_NAME}.TAB_PERFIL IS 'Armazena informações de perfil de usuário';
COMMENT ON COLUMN ${SCHEMA_NAME}.TAB_PERFIL.IDT_PERFIL
    IS 'Identificador artificial do perfil (Preenchido com o valor fornecido pela sequence SQ_PERFIL)';
COMMENT ON COLUMN ${SCHEMA_NAME}.TAB_PERFIL.NM_PERFIL IS 'Nome do perfil';
COMMENT ON COLUMN ${SCHEMA_NAME}.TAB_PERFIL.DS_PERFIL IS 'Descrição do perfil';
COMMENT ON COLUMN ${SCHEMA_NAME}.TAB_PERFIL.SGL_PERFIL IS 'Siglado perfil';
COMMENT ON COLUMN ${SCHEMA_NAME}.TAB_PERFIL.FLG_ATIVO IS 'Indica se perfil está ativo (S-SIM e N-NÃO)';
COMMENT ON COLUMN ${SCHEMA_NAME}.TAB_PERFIL.DAT_INCLUSAO IS 'Data de inclusão do registro';
COMMENT ON COLUMN ${SCHEMA_NAME}.TAB_PERFIL.DAT_ALTERACAO IS 'Data da última alteração do registro';

ALTER TABLE ${SCHEMA_NAME}.TAB_PERFIL
    ADD CONSTRAINT CK_PERFIL_01 CHECK (FLG_ATIVO IN ('S', 'N'));

ALTER TABLE ${SCHEMA_NAME}.TAB_PERFIL
    ADD CONSTRAINT UK_PERFIL_01 UNIQUE (SGL_PERFIL);

ALTER TABLE ${SCHEMA_NAME}.TAB_PERFIL
    ADD CONSTRAINT PK_PERFIL PRIMARY KEY (IDT_PERFIL);

CREATE SEQUENCE ${SCHEMA_NAME}.SQ_PERFIL
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    NO CYCLE
    OWNED BY ${SCHEMA_NAME}.TAB_PERFIL.IDT_PERFIL;

/*-------------------------------------------------------------------------------
-- GRANT'S
-------------------------------------------------------------------------------*/
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE ${SCHEMA_NAME}.TAB_PERFIL TO ${APP_USER};
GRANT USAGE ON SEQUENCE ${SCHEMA_NAME}.SQ_PERFIL TO ${APP_USER};
